name: 03 - Workflow Runners
on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the OS
        run: |
          echo "RUNNING on a ${{ runner.os }} 
          machine with ${{ runner.arch }} architecture."